#%%
# 1. Write some code to print out all the numbers from 1 to 10

for i in range(1, 11):
    print(i)

#%%
# 2.Write some code that prints out only the even numbers between 1 and 10

for i in range(1, 11):
    if i % 2 == 0:  # mod 2 = 0 means EVEN
        print(i)


#%%
# 3. Write some code that prints out only the even numbers between 1 and 1000

for i in range(1, 1001):
    if i % 2 == 0:  # mod 2 = 0 means EVEN
        print(i)


#%%
# 4. The opposite of a number is the number itself with its sign reversed. For example, the opposite of 1 is -1. The opposite of -6 is 6. Write some code to accept a numerical input from a user and print out the opposite of that input.

print(-int(input("Hi! Please enter in a number!")))


#%%
# 5. Write some code that prints out the numbers between 1 and 1000, but if the number is divisible by 3 it prints ‘fizz’, if the number is divisible by 5 it prints ‘buzz’ and if the number is divisible by 3 and 5 it prints ‘fizzbuzz’

for i in range(1, 1001):
    if i % 15 == 0:
        print("fizzbuzz")
    elif i % 3 == 0:
        print("fizz")
    elif i % 5 == 0:
        print("buzz")
    else:
        print(i)


#%%
# 6.	A square number is the product of a number multiplied by itself. Write some code that takes a numerical input from the user and prints out all the square numbers below that value.

user_input = input("Please enter a number")
i = 1

while i ** 2 < int(user_input):
    print(i ** 2)
    i += 1

#%%
"""
7.	The Fibonacci sequence starts with the values 1, 2. The next number in the sequence is generated by summing the previous 2 values, so the first 5 numbers in the sequence are:
1, 2, 3, 5, 8, …
a.	Write some code to generate the first 100 values in the Fibonacci sequence
b.	Write some code to add up only the even values in the first 1000 values of the Fibonacci sequence
"""

# 7a

a = 1
b = 2

print(a)
print(b)

for i in range(1, 101):
    print(a + b)
    b = b + a
    a = b - a

#%%
# 7b)

a = 1
b = 2
total = b


for i in range(1, 101):
    if (a + b) % 2 == 0:
        total += a + b
    b = b + a
    a = b - a

print(total)

#%%
# 8.	The sum of digits of a number is found by adding all the digits of a number together. For example, the sum of digits of 234 is 2 + 3 + 4 = 9. Write some code to take a numerical input from a user and print out the sum of digits of that number.

user_input = input("Please enter a number!")

print(f"You entered: {user_input}")  # f-strings

print(f"asdhkjhaskjdhkjashd {user_input=}")

total = 0

for letter in user_input:
    if letter.isnumeric():
        total += int(letter)

print(total)
